/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jikexueyuan_hellojni_JniBridge */

#ifndef _Included_com_jikexueyuan_hellojni_JniBridge
#define _Included_com_jikexueyuan_hellojni_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jikexueyuan_hellojni_JniBridge
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jikexueyuan_hellojni_JniBridge_getString
  (JNIEnv *, jclass);//将此函数拷贝到c++的源文件中去实现，参数2.为类（* Class: com_jikexueyuan_hellojni_JniBridge）的定义

/*
 * Class:     com_jikexueyuan_hellojni_JniBridge
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jikexueyuan_hellojni_JniBridge_getStr
  (JNIEnv *, jobject);//将此函数拷贝到c++的源文件中去实现，参数2.为当前类（* Class: com_jikexueyuan_hellojni_JniBridge）实例的this指针

/*
 * Class:     com_jikexueyuan_hellojni_JniBridge
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jikexueyuan_hellojni_JniBridge_add
  (JNIEnv *, jobject, jint, jint);//将此函数拷贝到c++的源文件中去实现，参数2.为当前类（* Class: com_jikexueyuan_hellojni_JniBridge）实例的this指针；参数3.jint其实就是int

#ifdef __cplusplus
}
#endif
#endif
